import type { Metadata } from "next";
import { buildMetadata } from "@/lib/seo";
import { Container, Section } from "@/components/site/ui";
import { Breadcrumbs } from "@/components/site/breadcrumbs";

export const metadata: Metadata = buildMetadata({
  title: "Terms of Use | TradePilot",
  description:
    "TradePilot terms of use: analysis software provided as-is, no financial advice, no profit guarantees, and the user's sole responsibility for trading decisions.",
  path: "/terms",
});

export default function TermsPage() {
  return (
    <>
      <Container className="pt-8">
        <Breadcrumbs items={[{ name: "Terms of use", path: "/terms" }]} />
      </Container>
      <Section ariaLabel="Terms of use">
        <Container>
          <div className="prose-tp mx-auto max-w-3xl space-y-6">
            <h1 className="text-3xl font-bold tracking-tight text-foreground">
              Terms of use
            </h1>
            <p>
              Last updated: August 14, 2026. By using TradePilot you agree to
              these terms. They exist to set honest expectations about what
              this software is — and is not.
            </p>

            <h2 className="text-xl font-bold text-foreground">
              1. Not financial advice
            </h2>
            <p>
              TradePilot provides educational content and rule-based market
              analysis generated by software. Nothing on the platform is a
              recommendation, solicitation or offer to buy or sell any
              financial instrument. We are not a broker, advisor or fund
              manager, and no communication from us should be interpreted as
              personalized investment advice.
            </p>

            <h2 className="text-xl font-bold text-foreground">
              2. Risk acknowledgment
            </h2>
            <p>
              Trading gold, silver, forex and other leveraged instruments
              involves substantial risk of loss and is not suitable for every
              investor. Historical and backtested performance has inherent
              limitations, does not reflect actual trading, and does not
              guarantee future results. You are solely responsible for your
              trading decisions and for the risk management around them.
            </p>

            <h2 className="text-xl font-bold text-foreground">
              3. Fair use of the service
            </h2>
            <p>
              You may use TradePilot for personal analysis and learning. You
              may not resell or redistribute platform outputs as your own
              signal service, scrape the platform at abusive rates, or use it
              in any way that violates applicable law.
            </p>

            <h2 className="text-xl font-bold text-foreground">
              4. Availability and accuracy
            </h2>
            <p>
              The service is provided &quot;as is&quot; without warranties of
              any kind. Market data may be delayed or occasionally incorrect;
              rules and models are updated over time; features may change. We
              will communicate material changes but do not guarantee
              uninterrupted availability.
            </p>

            <h2 className="text-xl font-bold text-foreground">
              5. Limitation of liability
            </h2>
            <p>
              To the maximum extent permitted by law, TradePilot is not liable
              for trading losses, missed opportunities, or damages arising
              from use of or reliance on the software. If this limitation is
              unenforceable in your jurisdiction, our total liability is
              limited to the fees you paid us in the preceding 12 months.
            </p>
          </div>
        </Container>
      </Section>
    </>
  );
}
